"""update id column to autoincreament

Revision ID: 49de33a94f78
Revises: 901f6b1df74c
Create Date: 2023-05-07 13:23:25.760468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49de33a94f78'
down_revision = '901f6b1df74c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
