"""update schema

Revision ID: 5c262f4966d1
Revises: 16a65f59a08c
Create Date: 2023-05-07 11:55:47.826049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c262f4966d1'
down_revision = '16a65f59a08c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_code'), 'tenants', ['code'], unique=True)
    op.create_index(op.f('ix_tenants_create_date'), 'tenants', ['create_date'], unique=False)
    op.create_index(op.f('ix_tenants_email'), 'tenants', ['email'], unique=False)
    op.create_index(op.f('ix_tenants_firstname'), 'tenants', ['firstname'], unique=False)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_lastname'), 'tenants', ['lastname'], unique=False)
    op.create_index(op.f('ix_tenants_phone'), 'tenants', ['phone'], unique=False)
    op.create_index(op.f('ix_tenants_update_date'), 'tenants', ['update_date'], unique=False)
    op.create_index(op.f('ix_tenants_user_id'), 'tenants', ['user_id'], unique=False)
    op.add_column('users', sa.Column('firstname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('lastname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_firstname'), 'users', ['firstname'], unique=False)
    op.create_index(op.f('ix_users_lastname'), 'users', ['lastname'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.add_column('visitors', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.drop_index('ix_visitors_user_id', table_name='visitors')
    op.create_index(op.f('ix_visitors_tenant_id'), 'visitors', ['tenant_id'], unique=False)
    op.drop_constraint('visitors_user_id_fkey', 'visitors', type_='foreignkey')
    op.create_foreign_key(None, 'visitors', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('visitors', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitors', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'visitors', type_='foreignkey')
    op.create_foreign_key('visitors_user_id_fkey', 'visitors', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_visitors_tenant_id'), table_name='visitors')
    op.create_index('ix_visitors_user_id', 'visitors', ['user_id'], unique=False)
    op.drop_column('visitors', 'tenant_id')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_lastname'), table_name='users')
    op.drop_index(op.f('ix_users_firstname'), table_name='users')
    op.drop_column('users', 'role')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    op.drop_index(op.f('ix_tenants_user_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_update_date'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_phone'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_lastname'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_firstname'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_email'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_create_date'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_code'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
