"""remove role from user table

Revision ID: 901f6b1df74c
Revises: 5c262f4966d1
Create Date: 2023-05-07 12:28:47.191391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901f6b1df74c'
down_revision = '5c262f4966d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_role', table_name='users')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    # ### end Alembic commands ###
